version: '3.8'
services:
    app:
        build: ./back
        container_name: app  
        environment:
            spring.datasource.url: "jdbc:mysql://db:3325/demo?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
            spring.datasource.username: "root"
            spring.datasource.password: "P@s5"
        ports:
            - 8080:8080
        volumes:
            - './back:/data'
volumes:
  app:
    driver: local