version: '3.8'
services:
    db_sql:
        container_name: db_sql
        image: mysql/mysql-server:latest
        environment:
            MYSQL_ROOT_PASSWORD: P@s5
            MYSQL_DATABASE: demo
        ports: 
            - 3325:3306
        volumes:
            - './db:/docker-entrypoint-initdb.d'
    app:
        container_name: app
        image: cu-java_app:1.0.0
        build: ./back
        depends_on:
            - db_sql
        env_file: './back/.env'
        ports:
            - 8080:8080
        volumes:
            - './back:/data'
volumes:
    db_sql:
        driver: local
    app:
        driver: local