version: '3.8'
services:
    app:
        build: ./back
        container_name: app  
        environment:
            - MYSQL_USER=root
            - MYSQL_PASSWORD=P@s5
            - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3325/demo
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=P@s5
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update    
        ports:
            - 8080:8080
        volumes:
            - './back:/data'
volumes:
  app:
    driver: local