version: '3.8'
services:
    app:
        build: ./back
        container_name: app  
        networks:
            - net-cm
        ports:
            - 8080:8080
        volumes:
            - './back:/data'
volumes:
  app:
    driver: local