version: '3.8'
services:
    db_sql:
        image: mysql/mysql-server:latest
        container_name: db_sql
        environment:
            MYSQL_ROOT_PASSWORD: P@s5
            MYSQL_DATABASE: demo
        ports: 
            - 3325:3306
        volumes:
            - './db:/docker-entrypoint-initdb.d'
    app:
        build: ./back
        container_name: app
        depends_on:
            - db_sql
        env_file: './back/.env'
        ports:
            - 8080:8080
        volumes:
            - './back:/data'
volumes:
  db_sql:
    driver: local
  app:
    driver: local