version: '3.8'
services:
    full_pgadmin:
        container_name: full_pgadmin
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_PASSWORD: admin
          PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
           - full_pgadmin:/var/lib/pgadmin
        ports:
        - 5050:80
    full_postgres:
        container_name: full_postgres
        image: postgres
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
           - full_postgres:/data/postgres
           - ./db_psql/demo.sql:/docker-entrypoint-initdb.d/create_tables.sql
        ports:
          - "5432:5432"      
    full_adminer:
        image: adminer:latest
        container_name: adminer
        restart: always
        ports:
          - 8888:8080
    full_db_sql:
        container_name: full_db_sql
        image: mysql/mysql-server:latest
        environment:
            MYSQL_ROOT_PASSWORD: P@s5
            MYSQL_DATABASE: demo
        ports:
            - 3325:3306
        volumes:
            - './db:/docker-entrypoint-initdb.d'
    full_app:
        container_name: full_app
        build: ./back
        depends_on:
            - full_db_sql
        env_file: './back/.env'
        ports:
            - 8080:8080
    full_citas_app:
        container_name: full_citas_app
        build: ./front
        ports:
            - 3000:3000
        volumes:
            - './:/app'
            - '/app/node_modules'
        depends_on:
            - full_app
volumes:
    full_db_sql:
        driver: local
    full_citas_app:
        driver: local
    full_postgres:
        driver: local
    full_pgadmin:
        driver: local